version: '3'

services:
  chaoschain:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./configs:/app/configs
    restart: unless-stopped
